apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app
      color: ${COLOR}
  template:
    metadata:
      labels:
        app: my-web-app
        color: ${COLOR}
    spec:
      containers:
      - name: my-web-app-container
        image: ${IMAGE_WITH_TAG}
        ports:
        - containerPort: 8080
