# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-web-app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    # This is the "switch". It will point to blue or green.
    # We start it by pointing to blue.
    app: my-web-app
    color: blue
